// pf2e.actionspf2e compendium item ids, so opening a generic action shows its system entry
// instead of a chat-guidance message. (stabilize/retch have no standalone entry.)
const ACTION_COMPENDIUM_IDS = {
  seek: "BlAOM2X92SI6HMtJ",
  "sense-motive": "1xRFPTFtWtGJ9ELw",
  demoralize: "2u915NdUyQan6uKF",
  "create-a-diversion": "GkmbTGfg8KcgynOA",
  feint: "QNAVeNKtHA0EUw4X",
  "tumble-through": "21WIfSu7Xd7uKqV8",
  balance: "M76ycLAqHoAgbcej",
  climb: "pprgrYQ1QnIDGZiy",
  swim: "c8TGiZ48ygoSPofx",
  "high-jump": "2HJ4yuEFY1Cast4h",
  "long-jump": "JUvAvruz7yRQXfz2",
  "force-open": "SjmKHgI7a5Z9JzBx",
  disarm: "Dt6B1slsBy8ipJu9",
  trip: "ge56Lu1xXVFYUnLP",
  grapple: "PMbdMWc2QroouFGD",
  reposition: "lOE4yjUnETTdaf2T",
  shove: "7blmbDrQFNfdT731",
  "raise-a-shield": "xjGwis0uaC2305pm",
  "take-cover": "ust1jJSCZQUhBZIz",
  escape: "SkZAQRkLLkmBQNB9",
  "recall-knowledge": "1OagaWtBpVXExToo",
  "administer-first-aid": "MHLuKy4nQO2Z4Am1",
  "command-an-animal": "q9nbyIF0PEBqMtYe",
  hide: "XMcnh4cSI32tljXa",
  sneak: "VMozDqMMuK5kpoX4",
  steal: "RDXXE7wMrSPCLv5k",
  "palm-an-object": "ijZ0DDFpMkWqaShd",
  stand: "OdIUybJ3ddfL7wzj",
  crawl: "Tj055UcNm6UEgtCg",
  step: "UHpkTuCtyaPqiCAB",
  stride: "Bcxarzksqt9ezrs6",
};

const GENERIC_ACTION_DEFS = [
  {
    id: "seek",
    name: "Seek",
    slug: "seek",
    actionCost: 1,
    role: "detection",
    skill: "perception",
    requiresSeekTarget: true,
    executable: "pf2e-action",
  },
  {
    id: "sense-motive",
    name: "Sense Motive",
    slug: "sense-motive",
    actionCost: 1,
    role: "detection",
    skill: "perception",
    hideFromSuggestions: true,
    requiresTarget: true,
    requiresCombatSignal: true,
    executable: "pf2e-action",
  },
  {
    id: "demoralize",
    name: "Demoralize",
    slug: "demoralize",
    actionCost: 1,
    role: "debuff",
    skill: "intimidation",
    targetSave: "will",
    requiresTarget: true,
    maxRange: 30,
    executable: "pf2e-action",
  },
  {
    id: "create-a-diversion",
    name: "Create a Diversion",
    slug: "create-a-diversion",
    actionCost: 1,
    role: "setup",
    skill: "deception",
    targetDefense: "perception",
    requiresNearbyEnemy: true,
    variant: "gesture",
    executable: "pf2e-action",
  },
  {
    id: "feint",
    name: "Feint",
    slug: "feint",
    actionCost: 1,
    role: "setup",
    skill: "deception",
    targetDefense: "perception",
    requiresEnemyInReach: true,
    executable: "pf2e-action",
  },
  {
    id: "tumble-through",
    name: "Tumble Through",
    slug: "tumble-through",
    actionCost: 1,
    role: "mobility",
    skill: "acrobatics",
    targetSave: "reflex",
    requiresNearbyEnemy: true,
    requiresTumbleThroughOpportunity: true,
    executable: "pf2e-action",
  },
  {
    id: "balance",
    name: "Balance",
    slug: "balance",
    actionCost: 1,
    role: "mobility",
    skill: "acrobatics",
    hideFromSuggestions: true,
    requiresTerrain: "balance",
    executable: "pf2e-action",
  },
  {
    id: "climb",
    name: "Climb",
    slug: "climb",
    actionCost: 1,
    role: "mobility",
    skill: "athletics",
    hideFromSuggestions: true,
    requiresTerrain: "climb",
    executable: "pf2e-action",
  },
  {
    id: "swim",
    name: "Swim",
    slug: "swim",
    actionCost: 1,
    role: "mobility",
    skill: "athletics",
    hideFromSuggestions: true,
    requiresTerrain: "swim",
    executable: "pf2e-action",
  },
  {
    id: "high-jump",
    name: "High Jump",
    slug: "high-jump",
    actionCost: 2,
    role: "mobility",
    skill: "athletics",
    hideFromSuggestions: true,
    executable: "pf2e-action",
  },
  {
    id: "long-jump",
    name: "Long Jump",
    slug: "long-jump",
    actionCost: 2,
    role: "mobility",
    skill: "athletics",
    hideFromSuggestions: true,
    executable: "pf2e-action",
  },
  {
    id: "force-open",
    name: "Force Open",
    slug: "force-open",
    actionCost: 1,
    role: "utility",
    skill: "athletics",
    hideFromSuggestions: true,
    attackTrait: true,
    requiresObstacleInReach: true,
    executable: "pf2e-action",
  },
  {
    id: "disarm",
    name: "Disarm",
    slug: "disarm",
    actionCost: 1,
    role: "control",
    skill: "athletics",
    targetSave: "reflex",
    requiresEnemyInReach: true,
    attackTrait: true,
    executable: "pf2e-action",
  },
  {
    id: "trip",
    name: "Trip",
    slug: "trip",
    actionCost: 1,
    role: "control",
    skill: "athletics",
    targetSave: "reflex",
    requiresEnemyInReach: true,
    attackTrait: true,
    executable: "pf2e-action",
  },
  {
    id: "grapple",
    name: "Grapple",
    slug: "grapple",
    actionCost: 1,
    role: "control",
    skill: "athletics",
    targetSave: "fortitude",
    requiresEnemyInReach: true,
    attackTrait: true,
    executable: "pf2e-action",
  },
  {
    id: "reposition",
    name: "Reposition",
    slug: "reposition",
    actionCost: 1,
    role: "control",
    skill: "athletics",
    targetSave: "fortitude",
    requiresEnemyInReach: true,
    attackTrait: true,
    executable: "pf2e-action",
  },
  {
    id: "shove",
    name: "Shove",
    slug: "shove",
    actionCost: 1,
    role: "control",
    skill: "athletics",
    targetSave: "fortitude",
    requiresEnemyInReach: true,
    attackTrait: true,
    executable: "pf2e-action",
  },
  {
    id: "raise-a-shield",
    name: "Raise a Shield",
    slug: "raise-a-shield",
    actionCost: 1,
    role: "defense",
    executable: "pf2e-action",
  },
  {
    id: "take-cover",
    name: "Take Cover",
    slug: "take-cover",
    actionCost: 1,
    role: "defense",
    // Only offered after Drop Prone, not from mere wall proximity -- a wall merely near the
    // token (behind it, or bounding an unrelated room) isn't real tactical cover, and this
    // module has no reliable way to tell a relevant wall from an irrelevant one.
    requiresProne: true,
    executable: "pf2e-action",
  },
  {
    id: "escape",
    name: "Escape",
    slug: "escape",
    actionCost: 1,
    role: "defense",
    attackTrait: true,
    requiresGrabbedOrRestrained: true,
    executable: "pf2e-action",
  },
  {
    id: "recall-knowledge",
    name: "Recall Knowledge",
    slug: "recall-knowledge",
    actionCost: 1,
    role: "knowledge",
    requiresTarget: true,
    playerFacing: true,
    executable: "recall-knowledge",
  },
  {
    id: "administer-first-aid",
    name: "Administer First Aid",
    slug: "administer-first-aid",
    actionCost: 2,
    role: "healing",
    skill: "medicine",
    requiresDyingOrBleedingAlly: true,
    executable: "pf2e-action",
  },
  {
    id: "stabilize",
    name: "Stabilize",
    slug: "stabilize",
    actionCost: 2,
    role: "healing",
    skill: "medicine",
    requiresDyingAlly: true,
    executable: "pf2e-action",
  },
  {
    id: "command-an-animal",
    name: "Command an Animal",
    slug: "command-an-animal",
    actionCost: 1,
    role: "support",
    skill: "nature",
    requiresCompanionOrMinion: true,
    executable: "pf2e-action",
  },
  {
    id: "hide",
    name: "Hide",
    slug: "hide",
    actionCost: 1,
    role: "defense",
    skill: "stealth",
    requiresCover: true,
    executable: "pf2e-action",
  },
  {
    id: "sneak",
    name: "Sneak",
    slug: "sneak",
    actionCost: 1,
    role: "mobility",
    skill: "stealth",
    requiresHiddenOrCover: true,
    executable: "pf2e-action",
  },
  {
    id: "steal",
    name: "Steal",
    slug: "steal",
    actionCost: 1,
    role: "utility",
    skill: "thievery",
    hideFromSuggestions: true,
    requiresEnemyInReach: true,
    requiresFreeHand: true,
    executable: "pf2e-action",
  },
  {
    id: "palm-an-object",
    name: "Palm an Object",
    slug: "palm-an-object",
    actionCost: 1,
    role: "utility",
    skill: "thievery",
    hideFromSuggestions: true,
    requiresObjectInReach: true,
    requiresFreeHand: true,
    executable: "pf2e-action",
  },
  {
    id: "stand",
    name: "Stand",
    slug: "stand",
    actionCost: 1,
    role: "mobility",
    traits: ["move"],
    activityProfile: { includes: ["move"], removesCondition: "prone" },
    requiresProne: true,
    executable: "pf2e-action",
  },
  {
    id: "crawl",
    name: "Crawl",
    slug: "crawl",
    actionCost: 1,
    role: "mobility",
    traits: ["move"],
    activityProfile: { includes: ["move", "crawl"], crawlDistance: 5 },
    requiresProne: true,
    executable: "pf2e-action",
  },
  {
    id: "retch",
    name: "Retch",
    slug: "retch",
    actionCost: 1,
    role: "recovery",
    activityProfile: { reducesCondition: "sickened" },
    requiresSickened: true,
    executable: "pf2e-action",
  },
  {
    id: "step",
    name: "Step",
    slug: "step",
    actionCost: 1,
    executable: "chat-guidance",
  },
  {
    id: "stride",
    name: "Stride",
    slug: "stride",
    actionCost: 1,
    executable: "chat-guidance",
  },
];

// Some actions are more useful explained by the condition they apply/remove/reduce than by their
// own (often one-line) action text — Stand/Crawl/Drop Prone are all about the Prone condition,
// Retch is entirely about reducing Sickened. Point those at the conditionitems compendium instead.
const ACTION_CONDITION_UUID_OVERRIDES = {
  stand: "Compendium.pf2e.conditionitems.Item.j91X7x0XSomq8d60", // Prone
  crawl: "Compendium.pf2e.conditionitems.Item.j91X7x0XSomq8d60", // Prone
  retch: "Compendium.pf2e.conditionitems.Item.fesd1n5eVhpCSS18", // Sickened
};

// Point each generic action at its pf2e.actionspf2e compendium entry so opening it shows the
// system details instead of a chat-guidance message.
export const GENERIC_ACTIONS = GENERIC_ACTION_DEFS.map((action) => {
  const conditionUuid = ACTION_CONDITION_UUID_OVERRIDES[action.slug];
  if (conditionUuid) return { ...action, uuid: conditionUuid };
  if (action.uuid) return action;
  const id = ACTION_COMPENDIUM_IDS[action.slug];
  return id ? { ...action, uuid: `Compendium.pf2e.actionspf2e.Item.${id}` } : action;
});
