export const GENERIC_ACTIONS = [
  {
    id: "seek",
    name: "Seek",
    slug: "seek",
    actionCost: 1,
    role: "detection",
    skill: "perception",
    requiresSeekTarget: true,
    executable: "pf2e-action",
  },
  {
    id: "sense-motive",
    name: "Sense Motive",
    slug: "sense-motive",
    actionCost: 1,
    role: "detection",
    skill: "perception",
    requiresTarget: true,
    requiresCombatSignal: true,
    executable: "pf2e-action",
  },
  {
    id: "demoralize",
    name: "Demoralize",
    slug: "demoralize",
    actionCost: 1,
    role: "debuff",
    skill: "intimidation",
    targetSave: "will",
    requiresTarget: true,
    maxRange: 30,
    executable: "pf2e-action",
  },
  {
    id: "create-a-diversion",
    name: "Create a Diversion",
    slug: "create-a-diversion",
    actionCost: 1,
    role: "setup",
    skill: "deception",
    targetDefense: "perception",
    requiresNearbyEnemy: true,
    variant: "gesture",
    executable: "pf2e-action",
  },
  {
    id: "feint",
    name: "Feint",
    slug: "feint",
    actionCost: 1,
    role: "setup",
    skill: "deception",
    targetDefense: "perception",
    requiresEnemyInReach: true,
    executable: "pf2e-action",
  },
  {
    id: "tumble-through",
    name: "Tumble Through",
    slug: "tumble-through",
    actionCost: 1,
    role: "mobility",
    skill: "acrobatics",
    targetSave: "reflex",
    requiresNearbyEnemy: true,
    requiresTumbleThroughOpportunity: true,
    executable: "pf2e-action",
  },
  {
    id: "balance",
    name: "Balance",
    slug: "balance",
    actionCost: 1,
    role: "mobility",
    skill: "acrobatics",
    requiresTerrain: "balance",
    executable: "pf2e-action",
  },
  {
    id: "climb",
    name: "Climb",
    slug: "climb",
    actionCost: 1,
    role: "mobility",
    skill: "athletics",
    requiresTerrain: "climb",
    executable: "pf2e-action",
  },
  {
    id: "swim",
    name: "Swim",
    slug: "swim",
    actionCost: 1,
    role: "mobility",
    skill: "athletics",
    requiresTerrain: "swim",
    executable: "pf2e-action",
  },
  {
    id: "high-jump",
    name: "High Jump",
    slug: "high-jump",
    actionCost: 2,
    role: "mobility",
    skill: "athletics",
    requiresTerrain: "jump",
    executable: "pf2e-action",
  },
  {
    id: "long-jump",
    name: "Long Jump",
    slug: "long-jump",
    actionCost: 2,
    role: "mobility",
    skill: "athletics",
    requiresTerrain: "jump",
    executable: "pf2e-action",
  },
  {
    id: "force-open",
    name: "Force Open",
    slug: "force-open",
    actionCost: 1,
    role: "utility",
    skill: "athletics",
    attackTrait: true,
    requiresObstacleInReach: true,
    executable: "pf2e-action",
  },
  {
    id: "disarm",
    name: "Disarm",
    slug: "disarm",
    actionCost: 1,
    role: "control",
    skill: "athletics",
    targetSave: "reflex",
    requiresEnemyInReach: true,
    attackTrait: true,
    executable: "pf2e-action",
  },
  {
    id: "trip",
    name: "Trip",
    slug: "trip",
    actionCost: 1,
    role: "control",
    skill: "athletics",
    targetSave: "reflex",
    requiresEnemyInReach: true,
    attackTrait: true,
    executable: "pf2e-action",
  },
  {
    id: "grapple",
    name: "Grapple",
    slug: "grapple",
    actionCost: 1,
    role: "control",
    skill: "athletics",
    targetSave: "fortitude",
    requiresEnemyInReach: true,
    attackTrait: true,
    executable: "pf2e-action",
  },
  {
    id: "reposition",
    name: "Reposition",
    slug: "reposition",
    actionCost: 1,
    role: "control",
    skill: "athletics",
    targetSave: "fortitude",
    requiresEnemyInReach: true,
    attackTrait: true,
    executable: "pf2e-action",
  },
  {
    id: "shove",
    name: "Shove",
    slug: "shove",
    actionCost: 1,
    role: "control",
    skill: "athletics",
    targetSave: "fortitude",
    requiresEnemyInReach: true,
    attackTrait: true,
    executable: "pf2e-action",
  },
  {
    id: "raise-a-shield",
    name: "Raise a Shield",
    slug: "raise-a-shield",
    actionCost: 1,
    role: "defense",
    executable: "pf2e-action",
  },
  {
    id: "take-cover",
    name: "Take Cover",
    slug: "take-cover",
    actionCost: 1,
    role: "defense",
    requiresCover: true,
    executable: "pf2e-action",
  },
  {
    id: "escape",
    name: "Escape",
    slug: "escape",
    actionCost: 1,
    role: "defense",
    attackTrait: true,
    requiresGrabbedOrRestrained: true,
    executable: "pf2e-action",
  },
  {
    id: "recall-knowledge",
    name: "Recall Knowledge",
    slug: "recall-knowledge",
    actionCost: 1,
    role: "knowledge",
    requiresTarget: true,
    playerFacing: true,
    executable: "chat-guidance",
  },
  {
    id: "administer-first-aid",
    name: "Administer First Aid",
    slug: "administer-first-aid",
    actionCost: 2,
    role: "healing",
    skill: "medicine",
    requiresDyingOrBleedingAlly: true,
    executable: "pf2e-action",
  },
  {
    id: "stabilize",
    name: "Stabilize",
    slug: "stabilize",
    actionCost: 2,
    role: "healing",
    skill: "medicine",
    requiresDyingAlly: true,
    executable: "pf2e-action",
  },
  {
    id: "command-an-animal",
    name: "Command an Animal",
    slug: "command-an-animal",
    actionCost: 1,
    role: "support",
    skill: "nature",
    requiresCompanionOrMinion: true,
    executable: "pf2e-action",
  },
  {
    id: "hide",
    name: "Hide",
    slug: "hide",
    actionCost: 1,
    role: "defense",
    skill: "stealth",
    requiresCover: true,
    executable: "pf2e-action",
  },
  {
    id: "sneak",
    name: "Sneak",
    slug: "sneak",
    actionCost: 1,
    role: "mobility",
    skill: "stealth",
    requiresHiddenOrCover: true,
    executable: "pf2e-action",
  },
  {
    id: "steal",
    name: "Steal",
    slug: "steal",
    actionCost: 1,
    role: "utility",
    skill: "thievery",
    requiresEnemyInReach: true,
    requiresFreeHand: true,
    executable: "pf2e-action",
  },
  {
    id: "palm-an-object",
    name: "Palm an Object",
    slug: "palm-an-object",
    actionCost: 1,
    role: "utility",
    skill: "thievery",
    requiresObjectInReach: true,
    requiresFreeHand: true,
    executable: "pf2e-action",
  },
  {
    id: "step",
    name: "Step",
    slug: "step",
    actionCost: 1,
    executable: "chat-guidance",
  },
  {
    id: "stride",
    name: "Stride",
    slug: "stride",
    actionCost: 1,
    executable: "chat-guidance",
  },
];
