import { ALCHEMIST_CLASS_TACTIC, ALCHEMIST_SUBCLASS_TACTICS } from "./alchemist.js";
import { ANIMIST_CLASS_TACTIC, ANIMIST_SUBCLASS_TACTICS } from "./animist.js";
import { BARBARIAN_CLASS_TACTIC, BARBARIAN_SUBCLASS_TACTICS } from "./barbarian.js";
import { BARD_CLASS_TACTIC, BARD_SUBCLASS_TACTICS } from "./bard.js";
import { CHAMPION_CLASS_TACTIC } from "./champion.js";
import { CLERIC_CLASS_TACTIC, CLERIC_SUBCLASS_TACTICS } from "./cleric.js";
import { COMMANDER_CLASS_TACTIC } from "./commander.js";
import { DRUID_CLASS_TACTIC, DRUID_SUBCLASS_TACTICS } from "./druid.js";
import { EXEMPLAR_CLASS_TACTIC, EXEMPLAR_SUBCLASS_TACTICS } from "./exemplar.js";
import { FIGHTER_CLASS_TACTIC } from "./fighter.js";
import { GUARDIAN_CLASS_TACTIC } from "./guardian.js";
import { GUNSLINGER_CLASS_TACTIC, GUNSLINGER_SUBCLASS_TACTICS } from "./gunslinger.js";
import { INVENTOR_CLASS_TACTIC, INVENTOR_SUBCLASS_TACTICS } from "./inventor.js";
import { INVESTIGATOR_CLASS_TACTIC, INVESTIGATOR_SUBCLASS_TACTICS } from "./investigator.js";
import { KINETICIST_CLASS_TACTIC, KINETICIST_SUBCLASS_TACTICS } from "./kineticist.js";
import { MAGUS_CLASS_TACTIC, MAGUS_SUBCLASS_TACTICS } from "./magus.js";
import { MONK_CLASS_TACTIC } from "./monk.js";
import { ORACLE_CLASS_TACTIC, ORACLE_SUBCLASS_TACTICS } from "./oracle.js";
import { PSYCHIC_CLASS_TACTIC, PSYCHIC_SUBCLASS_TACTICS } from "./psychic.js";
import { RANGER_CLASS_TACTIC, RANGER_SUBCLASS_TACTICS } from "./ranger.js";
import { ROGUE_CLASS_TACTIC, ROGUE_SUBCLASS_TACTICS } from "./rogue.js";
import { RUNESMITH_CLASS_TACTIC } from "./runesmith.js";
import { SORCERER_CLASS_TACTIC, SORCERER_SUBCLASS_TACTICS } from "./sorcerer.js";
import { SUMMONER_CLASS_TACTIC, SUMMONER_SUBCLASS_TACTICS } from "./summoner.js";
import { SWASHBUCKLER_CLASS_TACTIC, SWASHBUCKLER_SUBCLASS_TACTICS } from "./swashbuckler.js";
import { THAUMATURGE_CLASS_TACTIC, THAUMATURGE_SUBCLASS_TACTICS } from "./thaumaturge.js";
import { WITCH_CLASS_TACTIC, WITCH_SUBCLASS_TACTICS } from "./witch.js";
import { WIZARD_CLASS_TACTIC, WIZARD_SUBCLASS_TACTICS } from "./wizard.js";

export { SUBCLASS_TAGS } from "./subclasses.js";

export const CLASS_TACTICS = {
  "alchemist": ALCHEMIST_CLASS_TACTIC,
  "animist": ANIMIST_CLASS_TACTIC,
  "barbarian": BARBARIAN_CLASS_TACTIC,
  "bard": BARD_CLASS_TACTIC,
  "champion": CHAMPION_CLASS_TACTIC,
  "cleric": CLERIC_CLASS_TACTIC,
  "commander": COMMANDER_CLASS_TACTIC,
  "druid": DRUID_CLASS_TACTIC,
  "exemplar": EXEMPLAR_CLASS_TACTIC,
  "fighter": FIGHTER_CLASS_TACTIC,
  "guardian": GUARDIAN_CLASS_TACTIC,
  "gunslinger": GUNSLINGER_CLASS_TACTIC,
  "inventor": INVENTOR_CLASS_TACTIC,
  "investigator": INVESTIGATOR_CLASS_TACTIC,
  "kineticist": KINETICIST_CLASS_TACTIC,
  "magus": MAGUS_CLASS_TACTIC,
  "monk": MONK_CLASS_TACTIC,
  "oracle": ORACLE_CLASS_TACTIC,
  "psychic": PSYCHIC_CLASS_TACTIC,
  "ranger": RANGER_CLASS_TACTIC,
  "rogue": ROGUE_CLASS_TACTIC,
  "runesmith": RUNESMITH_CLASS_TACTIC,
  "sorcerer": SORCERER_CLASS_TACTIC,
  "summoner": SUMMONER_CLASS_TACTIC,
  "swashbuckler": SWASHBUCKLER_CLASS_TACTIC,
  "thaumaturge": THAUMATURGE_CLASS_TACTIC,
  "witch": WITCH_CLASS_TACTIC,
  "wizard": WIZARD_CLASS_TACTIC,
};

export const SUBCLASS_TACTICS = {
  ...ALCHEMIST_SUBCLASS_TACTICS,
  ...ANIMIST_SUBCLASS_TACTICS,
  ...BARBARIAN_SUBCLASS_TACTICS,
  ...BARD_SUBCLASS_TACTICS,
  ...CLERIC_SUBCLASS_TACTICS,
  ...DRUID_SUBCLASS_TACTICS,
  ...EXEMPLAR_SUBCLASS_TACTICS,
  ...GUNSLINGER_SUBCLASS_TACTICS,
  ...INVENTOR_SUBCLASS_TACTICS,
  ...INVESTIGATOR_SUBCLASS_TACTICS,
  ...KINETICIST_SUBCLASS_TACTICS,
  ...MAGUS_SUBCLASS_TACTICS,
  ...ORACLE_SUBCLASS_TACTICS,
  ...PSYCHIC_SUBCLASS_TACTICS,
  ...RANGER_SUBCLASS_TACTICS,
  ...ROGUE_SUBCLASS_TACTICS,
  ...SORCERER_SUBCLASS_TACTICS,
  ...SUMMONER_SUBCLASS_TACTICS,
  ...SWASHBUCKLER_SUBCLASS_TACTICS,
  ...THAUMATURGE_SUBCLASS_TACTICS,
  ...WITCH_SUBCLASS_TACTICS,
  ...WIZARD_SUBCLASS_TACTICS,
};

export const KNOWN_SUBCLASS_SLUGS = new Set(Object.keys(SUBCLASS_TACTICS));
